### ISSUE TITLE
2차 아이디어 및 리팩토링

### ISSUE THREAD

**Issue by deunlee** [TheStudyGroup/Sokoban#22]
### 개선 아이디어
+ [x] 맵에디터
+ [x] 타이머

### 보고서
+ [x] 리팩토링 10가지 이상 
+ [x] 보고서 작성 (문제점 및 개선 방법, 이유)
+ [x] 개선 전 Class Diagram 작성
+ [x] 개선 후 Class Diagram 작성
+ [x] 개선 후 Sequence Diagram 작성
+ [x] 발표 자료 (ppt)
+ [x] 발표 동영상 (5분 내외)

**Comment by deunlee** [comment]
역할분담 어떻게 했으면 좋을지 또는 1차과제 제출했을 때 코드 기준으로 리팩토링할 사항 있으면 코멘트 달아주세요.

---

STAN으로 보니까 tangle도 하나 있네요.
![aa](https://user-images.githubusercontent.com/54697735/99620589-2d9b0980-2a69-11eb-883f-02a3f67d4bd2.PNG)

**Comment by Sersoc** [comment]
말씀하신대로 하면 될 것 같습니다.

**Comment by deunlee** [comment]
@Sersoc 원하시는거 있으신가요?

**Comment by deunlee** [comment]
#23 리팩토링
